# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PortageXS
version:      0.01
version_from: PortageXS.pm
installdirs:  site
requires:
    Term::ANSIColor:               0
    Test::Simple:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
